version: '3.8'
services:
  nginx:
    image: nginx:latest
    container_name: ${CONTAINER_NAME_PREFIX}-nginx
    ports:
      - "80:80"
    volumes:
      - ${CODE_PATH}:/var/www:rw
      - ./nginx/logs:/var/log/nginx:rw
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf/conf.d:/etc/nginx/conf.d/:ro
    environment:
      - TZ=Asia/Shanghai
    restart: always
    networks:
      - default
  php:
    image: ccr.ccs.tencentyun.com/jormin/php-swoole:0.0.1
    container_name: ${CONTAINER_NAME_PREFIX}-php
    expose:
      - 9000
    volumes:
      - ${CODE_PATH}:/var/www:rw
      - ./php/conf:/usr/local/etc/php
      - ./php/logs:/var/log/php
    environment:
      - TZ=Asia/Shanghai
    restart: always
    networks:
      - default
  mysql:
    image: library/mysql:5.7.13
    container_name: ${CONTAINER_NAME_PREFIX}-mysql
    ports:
      - "3306:3306"
    networks:
      - default
    environment:
      MYSQL_ROOT_PASSWORD: dev
      MYSQL_DATABASE: dev
    volumes:
      - "./mysql/data:/var/lib/mysql"
    restart: always
  redis:
    image: redis:latest
    container_name: ${CONTAINER_NAME_PREFIX}-redis
    ports:
      - "6379:6379"
    volumes:
      - "./redis/data:/data"
    restart: always
    networks:
      - default

networks:
  default:
