version: '3.8'
services:
  nginx:
    image: nginx:latest
    container_name: ${CONTAINER_NAME_PREFIX}-nginx
    ports:
      - "80:80"
    volumes:
      - ${CODE_PATH}:/var/www:rw
      - ./nginx/logs:/var/log/nginx:rw
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf/conf.d:/etc/nginx/conf.d/:ro
    environment:
      - TZ=Asia/Shanghai
    restart: always
    networks:
      - ${NETWORK_NAME}
  php:
    image: ccr.ccs.tencentyun.com/jormin/php-swoole:0.0.1
    container_name: ${CONTAINER_NAME_PREFIX}-php
    expose:
      - 9000
    volumes:
      - ${CODE_PATH}:/var/www:rw
      - ./php/conf:/usr/local/etc/php
      - ./php/logs:/var/log/php
    environment:
      - TZ=Asia/Shanghai
    restart: always
    networks:
      - ${NETWORK_NAME}
  mysql:
    image: library/mysql:5.7.13
    container_name: ${CONTAINER_NAME_PREFIX}-mysql
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/conf:/etc/mysql
      - ./mysql/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    restart: always
    networks:
      - ${NETWORK_NAME}
  redis:
    image: redis:6.0.7
    container_name: ${CONTAINER_NAME_PREFIX}-redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis/conf:/etc/redis
      - ./redis/data:/data
    command: redis-server /etc/redis/redis.conf
    restart: always
    networks:
      - ${NETWORK_NAME}
  pma:
    image: phpmyadmin/phpmyadmin:latest
    container_name: ${CONTAINER_NAME_PREFIX}-pma
    ports:
      - 9090:80
    environment:
      - PMA_ARBITRARY=1
    restart: always
    networks:
      - ${NETWORK_NAME}

networks:
  ${NETWORK_NAME}:
