version: '3.8'
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ${CODE_PATH}:/var/www:rw
      - ./nginx/logs:/var/log/nginx:rw
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf/conf.d:/etc/nginx/conf.d/:ro
      - ./nginx/conf/certs:/etc/nginx/certs/:ro
    environment:
      - TZ=Asia/Shanghai
    restart: always
    networks:
      - devops
  php:
    build: ./php/
    container_name: php
    expose:
      - 9000
    volumes:
      - ${CODE_PATH}:/var/www:rw
      - ./php/conf:/usr/local/etc/php
      - ./php/logs:/var/log/php
    environment:
      - TZ=Asia/Shanghai
    restart: always
    networks:
      - devops
  mysql:
    image: library/mysql:5.7.13
    container_name: mysql
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - ./mysql/conf:/etc/mysql
      - ./mysql/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    restart: always
    networks:
      - devops
  redis:
    image: redis:6.0.7
    container_name: redis
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - ./redis/conf:/etc/redis
      - ./redis/data:/data
    command: redis-server /etc/redis/redis.conf
    restart: always
    networks:
      - devops
  etcd:
    image: quay.io/coreos/etcd:latest
    container_name: etcd
    ports:
      - "${ETCD_PORT}:2379"
    volumes:
      - ./etcd/data:/etcd-data
    entrypoint: /usr/local/bin/etcd
    command:
      - '--name=etcd1'
      - '--data-dir=/etcd_data'
      - '--initial-advertise-peer-urls=http://etcd1:2380'
      - '--listen-peer-urls=http://0.0.0.0:2380'
      - '--listen-client-urls=http://0.0.0.0:2379'
      - '--advertise-client-urls=http://etcd1:2379'
      - '--initial-cluster-token=mys1cr2tt1k7n'
      - '--heartbeat-interval=250'
      - '--election-timeout=1250'
      - '--initial-cluster=etcd1=http://etcd1:2380,etcd2=http://etcd2:2380,etcd3=http://etcd3:2380'
      - '--initial-cluster-state=new'
    restart: always
    networks:
      - devops

networks:
  devops:
    external: true