version: '3.8'
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ${CODE_PATH}:/var/www:rw
      - ./nginx/logs:/var/log/nginx:rw
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf/conf.d:/etc/nginx/conf.d/:ro
      - ./nginx/conf/certs:/etc/nginx/certs/:ro
    environment:
      - TZ=Asia/Shanghai
    restart: always
    networks:
      - web
  php:
    build: ./php/
    container_name: php
    expose:
      - 9000
    volumes:
      - ${CODE_PATH}:/var/www:rw
      - ./php/conf:/usr/local/etc/php
      - ./php/logs:/var/log/php
    environment:
      - TZ=Asia/Shanghai
    restart: always
    networks:
      - web
  mysql:
    image: library/mysql:5.7.13
    container_name: mysql
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - ./mysql/conf:/etc/mysql
      - ./mysql/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    restart: always
    networks:
      - web
  redis:
    image: redis:6.0.7
    container_name: redis
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - ./redis/conf:/etc/redis
      - ./redis/data:/data
    command: redis-server /etc/redis/redis.conf
    restart: always
    networks:
      - web

networks:
  web:
    external: true